apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    cloudfoundry.org/application_id: e25831e9-f3eb-484b-baf8-a0f1d4a58926
    cloudfoundry.org/application_name: kubecf-storefront-ui-app
    cloudfoundry.org/application_uris: '[{"hostname":"kubecf-storefront-ui-app-persistent-badger-eo.sf.kubecf.dev","port":8080}]'
    cloudfoundry.org/last_updated: "1590684686.0"
    cloudfoundry.org/original_request: '{"guid":"e25831e9-f3eb-484b-baf8-a0f1d4a58926","version":"601d4db1-7a9e-4c68-9d4b-c04287c5180b","process_guid":"e25831e9-f3eb-484b-baf8-a0f1d4a58926-601d4db1-7a9e-4c68-9d4b-c04287c5180b","process_type":"web","app_guid":"e25831e9-f3eb-484b-baf8-a0f1d4a58926","app_name":"kubecf-storefront-ui-app","space_guid":"e139e8df-01d8-44ba-b141-03400fc17613","space_name":"hello-worlds","organization_guid":"54ff329d-36fc-4db3-806d-47881878e915","organization_name":"examples","environment":{"VCAP_APPLICATION":"{\"cf_api\":\"https://api.sf.kubecf.dev\",\"limits\":{\"fds\":16384,\"mem\":512,\"disk\":1024},\"application_name\":\"kubecf-storefront-ui-app\",\"application_uris\":[\"kubecf-storefront-ui-app-persistent-badger-eo.sf.kubecf.dev\"],\"name\":\"kubecf-storefront-ui-app\",\"space_name\":\"hello-worlds\",\"space_id\":\"e139e8df-01d8-44ba-b141-03400fc17613\",\"organization_id\":\"54ff329d-36fc-4db3-806d-47881878e915\",\"organization_name\":\"examples\",\"uris\":[\"kubecf-storefront-ui-app-persistent-badger-eo.sf.kubecf.dev\"],\"process_id\":\"e25831e9-f3eb-484b-baf8-a0f1d4a58926\",\"process_type\":\"web\",\"application_id\":\"e25831e9-f3eb-484b-baf8-a0f1d4a58926\",\"version\":\"601d4db1-7a9e-4c68-9d4b-c04287c5180b\",\"application_version\":\"601d4db1-7a9e-4c68-9d4b-c04287c5180b\"}","MEMORY_LIMIT":"512m","VCAP_SERVICES":"{}","PORT":"8080","VCAP_APP_PORT":"8080","VCAP_APP_HOST":"0.0.0.0"},"egress_rules":[{"protocol":"all","destinations":["0.0.0.0-9.255.255.255"],"annotations":["security_group_id:384a2c4b-29e6-4f45-862e-13c8436db3e3"]},{"protocol":"all","destinations":["11.0.0.0-169.253.255.255"],"annotations":["security_group_id:384a2c4b-29e6-4f45-862e-13c8436db3e3"]},{"protocol":"all","destinations":["169.255.0.0-172.15.255.255"],"annotations":["security_group_id:384a2c4b-29e6-4f45-862e-13c8436db3e3"]},{"protocol":"all","destinations":["172.32.0.0-192.167.255.255"],"annotations":["security_group_id:384a2c4b-29e6-4f45-862e-13c8436db3e3"]},{"protocol":"all","destinations":["192.169.0.0-255.255.255.255"],"annotations":["security_group_id:384a2c4b-29e6-4f45-862e-13c8436db3e3"]},{"protocol":"tcp","destinations":["0.0.0.0/0"],"ports":[53],"annotations":["security_group_id:8aacf96f-021c-4121-91ab-44543335893e"]},{"protocol":"udp","destinations":["0.0.0.0/0"],"ports":[53],"annotations":["security_group_id:8aacf96f-021c-4121-91ab-44543335893e"]},{"protocol":"tcp","destinations":["172.30.241.50/32"],"ports":[8443],"annotations":["security_group_id:b435f80a-5c70-4881-9d1f-938cc2df1729"]},{"protocol":"tcp","destinations":["172.30.241.49/32"],"ports":[8844],"annotations":["security_group_id:073ab53b-90bf-47b9-bbb8-008d01c9b937"]}],"placement_tags":[],"instances":1,"memory_mb":512,"disk_mb":1024,"cpu_weight":6,"health_check_type":"port","health_check_http_endpoint":"","health_check_timeout_ms":0,"start_timeout_ms":60000,"last_updated":"1590684686.0","volume_mounts":[],"ports":[8080],"routes":{"cf-router":[{"hostname":"kubecf-storefront-ui-app-persistent-badger-eo.sf.kubecf.dev","port":8080}]},"lifecycle":{"buildpack_lifecycle":{"start_command":"npm
      start","droplet_hash":"6f1fdbd244966a8833886ef021b601e4dd83e8d2","droplet_guid":"0561e479-08cf-46e6-b412-ef4328f39741"}},"user_defined_annotations":{}}'
    cloudfoundry.org/process_guid: e25831e9-f3eb-484b-baf8-a0f1d4a58926-601d4db1-7a9e-4c68-9d4b-c04287c5180b
    cloudfoundry.org/routes: '[{"hostname":"kubecf-storefront-ui-app-persistent-badger-eo.sf.kubecf.dev","port":8080}]'
    cloudfoundry.org/space_name: hello-worlds
    cloudfoundry.org/version: 601d4db1-7a9e-4c68-9d4b-c04287c5180b
  creationTimestamp: "2020-05-28T16:51:26Z"
  generation: 1
  labels:
    cloudfoundry.org/app_guid: e25831e9-f3eb-484b-baf8-a0f1d4a58926
    cloudfoundry.org/guid: e25831e9-f3eb-484b-baf8-a0f1d4a58926
    cloudfoundry.org/process_type: web
    cloudfoundry.org/rootfs-version: ""
    cloudfoundry.org/source_type: APP
    cloudfoundry.org/version: 601d4db1-7a9e-4c68-9d4b-c04287c5180b
  name: kubecf-storefront-ui-app-hello-worlds-565cd2c0b9
  namespace: kubecf-eirini
  resourceVersion: "37373623"
  selfLink: /apis/apps/v1/namespaces/kubecf-eirini/statefulsets/kubecf-storefront-ui-app-hello-worlds-565cd2c0b9
  uid: c1fee154-76d8-4e15-b6ae-c98862968549
spec:
  podManagementPolicy: Parallel
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      cloudfoundry.org/guid: e25831e9-f3eb-484b-baf8-a0f1d4a58926
      cloudfoundry.org/source_type: APP
      cloudfoundry.org/version: 601d4db1-7a9e-4c68-9d4b-c04287c5180b
  serviceName: ""
  template:
    metadata:
      annotations:
        cloudfoundry.org/application_id: e25831e9-f3eb-484b-baf8-a0f1d4a58926
        cloudfoundry.org/process_guid: e25831e9-f3eb-484b-baf8-a0f1d4a58926-601d4db1-7a9e-4c68-9d4b-c04287c5180b
        seccomp.security.alpha.kubernetes.io/pod: runtime/default
      creationTimestamp: null
      labels:
        cloudfoundry.org/app_guid: e25831e9-f3eb-484b-baf8-a0f1d4a58926
        cloudfoundry.org/guid: e25831e9-f3eb-484b-baf8-a0f1d4a58926
        cloudfoundry.org/process_type: web
        cloudfoundry.org/rootfs-version: ""
        cloudfoundry.org/source_type: APP
        cloudfoundry.org/version: 601d4db1-7a9e-4c68-9d4b-c04287c5180b
    spec:
      automountServiceAccountToken: false
      containers:
      - command:
        - dumb-init
        - --
        - /lifecycle/launch
        env:
        - name: START_COMMAND
          value: npm start
        - name: VCAP_SERVICES
          value: '{}'
        - name: VCAP_APP_PORT
          value: "8080"
        - name: VCAP_APP_HOST
          value: 0.0.0.0
        - name: MEMORY_LIMIT
          value: 512m
        - name: CF_INSTANCE_PORTS
          value: '[{"external":8080,"internal":8080}]'
        - name: PATH
          value: /usr/local/bin:/usr/bin:/bin
        - name: TMPDIR
          value: /home/vcap/tmp
        - name: VCAP_APPLICATION
          value: '{"cf_api":"https://api.sf.kubecf.dev","limits":{"fds":16384,"mem":512,"disk":1024},"application_name":"kubecf-storefront-ui-app","application_uris":["kubecf-storefront-ui-app-persistent-badger-eo.sf.kubecf.dev"],"name":"kubecf-storefront-ui-app","space_name":"hello-worlds","space_id":"e139e8df-01d8-44ba-b141-03400fc17613","organization_id":"54ff329d-36fc-4db3-806d-47881878e915","organization_name":"examples","uris":["kubecf-storefront-ui-app-persistent-badger-eo.sf.kubecf.dev"],"process_id":"e25831e9-f3eb-484b-baf8-a0f1d4a58926","process_type":"web","application_id":"e25831e9-f3eb-484b-baf8-a0f1d4a58926","version":"601d4db1-7a9e-4c68-9d4b-c04287c5180b","application_version":"601d4db1-7a9e-4c68-9d4b-c04287c5180b"}'
        - name: USER
          value: vcap
        - name: CF_INSTANCE_ADDR
          value: 0.0.0.0:8080
        - name: PORT
          value: "8080"
        - name: LANG
          value: en_US.UTF-8
        - name: HOME
          value: /home/vcap/app
        - name: CF_INSTANCE_PORT
          value: "8080"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: CF_INSTANCE_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: CF_INSTANCE_INTERNAL_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        image: 127.0.0.1:32123/cloudfoundry/0561e479-08cf-46e6-b412-ef4328f39741:6f1fdbd244966a8833886ef021b601e4dd83e8d2
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 4
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 8080
          timeoutSeconds: 1
        name: opi
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          failureThreshold: 1
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 8080
          timeoutSeconds: 1
        resources:
          limits:
            ephemeral-storage: 1024M
            memory: 512M
          requests:
            cpu: 60m
            memory: 512M
        securityContext:
          allowPrivilegeEscalation: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: bits-service-registry-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
status:
  collisionCount: 0
  currentReplicas: 1
  currentRevision: kubecf-storefront-ui-app-hello-worlds-565cd2c0b9-ff9bfcd89
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updateRevision: kubecf-storefront-ui-app-hello-worlds-565cd2c0b9-ff9bfcd89
  updatedReplicas: 1
