apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    cloudfoundry.org/application_id: 8fbb6a9d-62fb-4619-9250-be2818d9f2cf
    cloudfoundry.org/application_name: test-spring-app
    cloudfoundry.org/application_uris: '[{"hostname":"test-spring-app-boring-cat-uy.sf.kubecf.dev","port":8080}]'
    cloudfoundry.org/last_updated: "1590171892.0"
    cloudfoundry.org/original_request: '{"guid":"8fbb6a9d-62fb-4619-9250-be2818d9f2cf","version":"3e3cc3e2-2465-4096-a7dc-e93dbc286e03","process_guid":"8fbb6a9d-62fb-4619-9250-be2818d9f2cf-3e3cc3e2-2465-4096-a7dc-e93dbc286e03","process_type":"web","app_guid":"8fbb6a9d-62fb-4619-9250-be2818d9f2cf","app_name":"test-spring-app","space_guid":"e139e8df-01d8-44ba-b141-03400fc17613","space_name":"hello-worlds","organization_guid":"54ff329d-36fc-4db3-806d-47881878e915","organization_name":"examples","environment":{"VCAP_APPLICATION":"{\"cf_api\":\"https://api.sf.kubecf.dev\",\"limits\":{\"fds\":16384,\"mem\":768,\"disk\":1024},\"application_name\":\"test-spring-app\",\"application_uris\":[\"test-spring-app-boring-cat-uy.sf.kubecf.dev\"],\"name\":\"test-spring-app\",\"space_name\":\"hello-worlds\",\"space_id\":\"e139e8df-01d8-44ba-b141-03400fc17613\",\"organization_id\":\"54ff329d-36fc-4db3-806d-47881878e915\",\"organization_name\":\"examples\",\"uris\":[\"test-spring-app-boring-cat-uy.sf.kubecf.dev\"],\"process_id\":\"8fbb6a9d-62fb-4619-9250-be2818d9f2cf\",\"process_type\":\"web\",\"application_id\":\"8fbb6a9d-62fb-4619-9250-be2818d9f2cf\",\"version\":\"3e3cc3e2-2465-4096-a7dc-e93dbc286e03\",\"application_version\":\"3e3cc3e2-2465-4096-a7dc-e93dbc286e03\"}","MEMORY_LIMIT":"768m","VCAP_SERVICES":"{}","PORT":"8080","VCAP_APP_PORT":"8080","VCAP_APP_HOST":"0.0.0.0"},"egress_rules":[{"protocol":"all","destinations":["0.0.0.0-9.255.255.255"],"annotations":["security_group_id:384a2c4b-29e6-4f45-862e-13c8436db3e3"]},{"protocol":"all","destinations":["11.0.0.0-169.253.255.255"],"annotations":["security_group_id:384a2c4b-29e6-4f45-862e-13c8436db3e3"]},{"protocol":"all","destinations":["169.255.0.0-172.15.255.255"],"annotations":["security_group_id:384a2c4b-29e6-4f45-862e-13c8436db3e3"]},{"protocol":"all","destinations":["172.32.0.0-192.167.255.255"],"annotations":["security_group_id:384a2c4b-29e6-4f45-862e-13c8436db3e3"]},{"protocol":"all","destinations":["192.169.0.0-255.255.255.255"],"annotations":["security_group_id:384a2c4b-29e6-4f45-862e-13c8436db3e3"]},{"protocol":"tcp","destinations":["0.0.0.0/0"],"ports":[53],"annotations":["security_group_id:8aacf96f-021c-4121-91ab-44543335893e"]},{"protocol":"udp","destinations":["0.0.0.0/0"],"ports":[53],"annotations":["security_group_id:8aacf96f-021c-4121-91ab-44543335893e"]},{"protocol":"tcp","destinations":["172.30.241.50/32"],"ports":[8443],"annotations":["security_group_id:b435f80a-5c70-4881-9d1f-938cc2df1729"]},{"protocol":"tcp","destinations":["172.30.241.49/32"],"ports":[8844],"annotations":["security_group_id:073ab53b-90bf-47b9-bbb8-008d01c9b937"]}],"placement_tags":[],"instances":1,"memory_mb":768,"disk_mb":1024,"cpu_weight":9,"health_check_type":"port","health_check_http_endpoint":null,"health_check_timeout_ms":0,"start_timeout_ms":60000,"last_updated":"1590171892.0","volume_mounts":[],"ports":[8080],"routes":{"cf-router":[{"hostname":"test-spring-app-boring-cat-uy.sf.kubecf.dev","port":8080}]},"lifecycle":{"buildpack_lifecycle":{"start_command":"JAVA_OPTS=\"-agentpath:$PWD/.java-buildpack/open_jdk_jre/bin/jvmkill-1.16.0_RELEASE=printHeapHistogram=1
      -Djava.io.tmpdir=$TMPDIR -XX:ActiveProcessorCount=$(nproc) -Djava.ext.dirs=$PWD/.java-buildpack/container_security_provider:$PWD/.java-buildpack/open_jdk_jre/lib/ext
      -Djava.security.properties=$PWD/.java-buildpack/java_security/java.security
      $JAVA_OPTS\" && CALCULATED_MEMORY=$($PWD/.java-buildpack/open_jdk_jre/bin/java-buildpack-memory-calculator-3.13.0_RELEASE
      -totMemory=$MEMORY_LIMIT -loadedClasses=8368 -poolType=metaspace -stackThreads=250
      -vmOptions=\"$JAVA_OPTS\") && echo JVM Memory Configuration: $CALCULATED_MEMORY
      && JAVA_OPTS=\"$JAVA_OPTS $CALCULATED_MEMORY\" && MALLOC_ARENA_MAX=2 JAVA_OPTS=$JAVA_OPTS
      SERVER_PORT=$PORT JAVA_HOME=$PWD/.java-buildpack/open_jdk_jre exec $PWD/.java-buildpack/spring_boot_cli/bin/spring
      run -cp $PWD/.java-buildpack/client_certificate_mapper/client_certificate_mapper-1.11.0_RELEASE.jar
      app.groovy","droplet_hash":"b0d561ab86259986dee19d427fec5590eb4d9ac2","droplet_guid":"e9508e43-5c11-45d7-934b-2ec46e830b15"}},"user_defined_annotations":{}}'
    cloudfoundry.org/process_guid: 8fbb6a9d-62fb-4619-9250-be2818d9f2cf-3e3cc3e2-2465-4096-a7dc-e93dbc286e03
    cloudfoundry.org/routes: '[{"hostname":"test-spring-app-boring-cat-uy.sf.kubecf.dev","port":8080}]'
    cloudfoundry.org/space_name: hello-worlds
    cloudfoundry.org/version: 3e3cc3e2-2465-4096-a7dc-e93dbc286e03
  creationTimestamp: "2020-05-22T18:24:52Z"
  generation: 1
  labels:
    cloudfoundry.org/app_guid: 8fbb6a9d-62fb-4619-9250-be2818d9f2cf
    cloudfoundry.org/guid: 8fbb6a9d-62fb-4619-9250-be2818d9f2cf
    cloudfoundry.org/process_type: web
    cloudfoundry.org/rootfs-version: ""
    cloudfoundry.org/source_type: APP
    cloudfoundry.org/version: 3e3cc3e2-2465-4096-a7dc-e93dbc286e03
  name: test-spring-app-hello-worlds-e6ff2121c5
  namespace: kubecf-eirini
  resourceVersion: "30801718"
  selfLink: /apis/apps/v1/namespaces/kubecf-eirini/statefulsets/test-spring-app-hello-worlds-e6ff2121c5
  uid: 82f4c3b4-60f4-48c7-8c8a-84fd710530e7
spec:
  podManagementPolicy: Parallel
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      cloudfoundry.org/guid: 8fbb6a9d-62fb-4619-9250-be2818d9f2cf
      cloudfoundry.org/source_type: APP
      cloudfoundry.org/version: 3e3cc3e2-2465-4096-a7dc-e93dbc286e03
  serviceName: ""
  template:
    metadata:
      annotations:
        cloudfoundry.org/application_id: 8fbb6a9d-62fb-4619-9250-be2818d9f2cf
        cloudfoundry.org/process_guid: 8fbb6a9d-62fb-4619-9250-be2818d9f2cf-3e3cc3e2-2465-4096-a7dc-e93dbc286e03
        seccomp.security.alpha.kubernetes.io/pod: runtime/default
      creationTimestamp: null
      labels:
        cloudfoundry.org/app_guid: 8fbb6a9d-62fb-4619-9250-be2818d9f2cf
        cloudfoundry.org/guid: 8fbb6a9d-62fb-4619-9250-be2818d9f2cf
        cloudfoundry.org/process_type: web
        cloudfoundry.org/rootfs-version: ""
        cloudfoundry.org/source_type: APP
        cloudfoundry.org/version: 3e3cc3e2-2465-4096-a7dc-e93dbc286e03
    spec:
      automountServiceAccountToken: false
      containers:
      - command:
        - dumb-init
        - --
        - /lifecycle/launch
        env:
        - name: PORT
          value: "8080"
        - name: CF_INSTANCE_ADDR
          value: 0.0.0.0:8080
        - name: TMPDIR
          value: /home/vcap/tmp
        - name: HOME
          value: /home/vcap/app
        - name: VCAP_SERVICES
          value: '{}'
        - name: START_COMMAND
          value: 'JAVA_OPTS="-agentpath:$PWD/.java-buildpack/open_jdk_jre/bin/jvmkill-1.16.0_RELEASE=printHeapHistogram=1
            -Djava.io.tmpdir=$TMPDIR -XX:ActiveProcessorCount=$(nproc) -Djava.ext.dirs=$PWD/.java-buildpack/container_security_provider:$PWD/.java-buildpack/open_jdk_jre/lib/ext
            -Djava.security.properties=$PWD/.java-buildpack/java_security/java.security
            $JAVA_OPTS" && CALCULATED_MEMORY=$($PWD/.java-buildpack/open_jdk_jre/bin/java-buildpack-memory-calculator-3.13.0_RELEASE
            -totMemory=$MEMORY_LIMIT -loadedClasses=8368 -poolType=metaspace -stackThreads=250
            -vmOptions="$JAVA_OPTS") && echo JVM Memory Configuration: $CALCULATED_MEMORY
            && JAVA_OPTS="$JAVA_OPTS $CALCULATED_MEMORY" && MALLOC_ARENA_MAX=2 JAVA_OPTS=$JAVA_OPTS
            SERVER_PORT=$PORT JAVA_HOME=$PWD/.java-buildpack/open_jdk_jre exec $PWD/.java-buildpack/spring_boot_cli/bin/spring
            run -cp $PWD/.java-buildpack/client_certificate_mapper/client_certificate_mapper-1.11.0_RELEASE.jar
            app.groovy'
        - name: PATH
          value: /usr/local/bin:/usr/bin:/bin
        - name: VCAP_APPLICATION
          value: '{"cf_api":"https://api.sf.kubecf.dev","limits":{"fds":16384,"mem":768,"disk":1024},"application_name":"test-spring-app","application_uris":["test-spring-app-boring-cat-uy.sf.kubecf.dev"],"name":"test-spring-app","space_name":"hello-worlds","space_id":"e139e8df-01d8-44ba-b141-03400fc17613","organization_id":"54ff329d-36fc-4db3-806d-47881878e915","organization_name":"examples","uris":["test-spring-app-boring-cat-uy.sf.kubecf.dev"],"process_id":"8fbb6a9d-62fb-4619-9250-be2818d9f2cf","process_type":"web","application_id":"8fbb6a9d-62fb-4619-9250-be2818d9f2cf","version":"3e3cc3e2-2465-4096-a7dc-e93dbc286e03","application_version":"3e3cc3e2-2465-4096-a7dc-e93dbc286e03"}'
        - name: VCAP_APP_HOST
          value: 0.0.0.0
        - name: USER
          value: vcap
        - name: CF_INSTANCE_PORTS
          value: '[{"external":8080,"internal":8080}]'
        - name: MEMORY_LIMIT
          value: 768m
        - name: VCAP_APP_PORT
          value: "8080"
        - name: LANG
          value: en_US.UTF-8
        - name: CF_INSTANCE_PORT
          value: "8080"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: CF_INSTANCE_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: CF_INSTANCE_INTERNAL_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        image: 127.0.0.1:32123/cloudfoundry/e9508e43-5c11-45d7-934b-2ec46e830b15:b0d561ab86259986dee19d427fec5590eb4d9ac2
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 4
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 8080
          timeoutSeconds: 1
        name: opi
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          failureThreshold: 1
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 8080
          timeoutSeconds: 1
        resources:
          limits:
            ephemeral-storage: 1024M
            memory: 768M
          requests:
            cpu: 90m
            memory: 768M
        securityContext:
          allowPrivilegeEscalation: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: bits-service-registry-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
status:
  collisionCount: 0
  currentReplicas: 1
  currentRevision: test-spring-app-hello-worlds-e6ff2121c5-6d78cdbf4c
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updateRevision: test-spring-app-hello-worlds-e6ff2121c5-6d78cdbf4c
  updatedReplicas: 1
